DROP TABLE IF EXISTS `OWNER_MASTER`;
CREATE TABLE IF NOT EXISTS`OWNER_MASTER` (
 `ID` int(7) NOT NULL AUTO_INCREMENT,
 `FIRST_NAME` varchar(50) NOT NULL,
 `LAST_NAME` varchar(50) NOT NULL,
 `PHONE_NUM` varchar(10) NOT NULL,
 `HOUSE_NUM` varchar(50) NOT NULL,
 `HOUSE_STREET` varchar(100) NOT NULL,
 `HOUSE_CITY` varchar(50) NOT NULL,
 `HOUSE_STATE` varchar(50) NOT NULL,
 `HOUSE_ZIP` int(5) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `PERMITEE_MASTER`;
CREATE TABLE `PERMITEE_MASTER` (
 `ID` int(7) NOT NULL AUTO_INCREMENT,
 `LICENSE_NUM` int(15) NOT NULL DEFAULT '0',
 `LICENSE_TYPE` varchar(100) NOT NULL,
 `FIRST_NAME` varchar(50) NOT NULL,
 `LAST_NAME` varchar(50) NOT NULL,
 `BUS_NAME` varchar(50) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `LICENSE_NUM` (`LICENSE_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `PERMIT_DETAILS`;
CREATE TABLE `PERMIT_DETAILS` (
 `ID` int(7) NOT NULL AUTO_INCREMENT,
 `BIN_NUM` varchar(10) NOT NULL,
 `HOUSE_NUM` varchar(100) NOT NULL,
 `JOB_TYPE` varchar(50) NOT NULL DEFAULT '',
 `PERMIT_TYPE` varchar(50) NOT NULL,
 `PERMIT_SUBTYPE` varchar(50) NOT NULL DEFAULT '',
 `PERMIT_WORKTYPE` varchar(50) NOT NULL DEFAULT '',
 `SEQUENCE_NUM` varchar(10) NOT NULL,
 `FILING_DATE` date NOT NULL DEFAULT '0000-00-00',
 `ISSUANCE_DATE` date DEFAULT NULL,
 `EXPIRATION_DATE` date DEFAULT NULL,
 `PERMIT_STATUS` varchar(50) NOT NULL,
 `JOB_START_DATE` date DEFAULT NULL,
 `FILING_STATUS` varchar(50) NOT NULL,
 `PERMIT_ID` int(7) NOT NULL,
 `PERMITEE_ID` int(7) NOT NULL,
 `OWNER_ID` int(7) NOT NULL,
 `HOUSE_STREET` varchar(100) NOT NULL,
 `HOUSE_BOROUGH` varchar(100) NOT NULL,
 `HOUSE_ZIP` int(5) NOT NULL,
 PRIMARY KEY (`ID`,`BIN_NUM`,`HOUSE_NUM`,`JOB_TYPE`,`PERMIT_TYPE`,`PERMIT_SUBTYPE`,`PERMIT_WORKTYPE`,`SEQUENCE_NUM`,`FILING_DATE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `PERMIT_MASTER`;
CREATE TABLE `PERMIT_MASTER` (
  `ID` int(7) NOT NULL AUTO_INCREMENT,
  `JOB_TYPE` varchar(5) NOT NULL,
  `PERMIT_TYPE` varchar(5) NOT NULL,
  `PERMIT_SUBTYPE` varchar(5) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=32 ;

CREATE TABLE `OWNER_PREFERENCES` (
 `OWNER_ID` bigint(20) NOT NULL,
 `PERMIT_ID` bigint(20) NOT NULL,
 `PREFERENCE` int(11) NOT NULL,
 PRIMARY KEY (`OWNER_ID`,`PERMIT_ID`),
 KEY `OWNER_ID` (`OWNER_ID`),
 KEY `PERMIT_ID` (`PERMIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

INSERT INTO `PERMIT_MASTER` (`ID`, `JOB_TYPE`, `PERMIT_TYPE`, `PERMIT_SUBTYPE`) VALUES
(1, 'A1', 'AL', 'N/A'),
(2, 'A1', 'EQ', 'FN'),
(3, 'A1', 'FO', 'EA'),
(4, 'A1', 'FO', 'N/A'),
(5, 'A1', 'PL', 'N/A'),
(6, 'A2', 'EQ', 'FN'),
(7, 'A2', 'EQ', 'OT'),
(8, 'A2', 'EQ', 'SF'),
(9, 'A2', 'EQ', 'SH'),
(10, 'A2', 'EW', 'BL'),
(11, 'A2', 'EW', 'FB'),
(12, 'A2', 'EW', 'FP'),
(13, 'A2', 'EW', 'FS'),
(14, 'A2', 'EW', 'MH'),
(15, 'A2', 'EW', 'OT'),
(16, 'A2', 'EW', 'SD'),
(17, 'A2', 'EW', 'SP'),
(18, 'A2', 'PL', 'N/A'),
(19, 'A3', 'AL', 'N/A'),
(20, 'A3', 'EQ', 'CH'),
(21, 'A3', 'EQ', 'FN'),
(22, 'A3', 'EQ', 'OT'),
(23, 'A3', 'EQ', 'SF'),
(24, 'A3', 'EQ', 'SH'),
(25, 'NB', 'EQ', 'CH'),
(26, 'NB', 'EQ', 'FN'),
(27, 'NB', 'FO', 'EA'),
(28, 'NB', 'FO', 'N/A'),
(29, 'NB', 'NB', 'N/A'),
(30, 'NB', 'PL', 'N/A');